version: 2

sources:
  - name: raw
    database: ecommerce_db        # your database name
    schema: raw      # where raw tables exist
    tables:
      - name: orders
      - name: customers
      - name: products
      
